from .institution import Institution
from .analytics import Analytics
from .requisites import Requisites
from .work_hours import WorkHours
from .design import Design
from .banner import Banner
from .social_links import SocialLinks
from .extra_phone import ExtraPhone
from .min_cart_cost import MinCartCost
from .organization_timezone import OrganizationTimeZone
