import os

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER')
CELERY_EAGER_PROPAGATES_EXCEPTIONS = True
CELERY_BROKER_CONNECTION_TIMEOUT = 20
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = os.environ.get('CELERY_BACKEND')
# CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
